title: Marcelo L. Lopez Photography
url:  http://127.0.0.1:4000
baseurl: /mlopezphoto

author: Marcelo Lopez Lopez
description: Bronx~NYC Based Portrait Photographer & Political Creative.

include: ['_pages']

collections_dir: series

collections:
#  home:
#    output: true
#  davgil:
#    output: true
#  friends:
#    output: true
#  headshots:
#    output: true

markdown: kramdown
kramdown:
  input: GFM
